### ISSUE TITLE
An error occurred while loading the plugin.

### ISSUE THREAD

**Issue by Ghost067** [promcteam/codex#19]
The following is a record of the error.

[14:33:11 ERROR]: Error occurred while enabling Codex v1.0.0-R0.1-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/generator/WorldInfo
        at studio.magemonkey.codex.legacy.placeholder.PlaceholderRegistry.load(PlaceholderRegistry.java:93) ~[?:?]
        at studio.magemonkey.codex.CodexEngine.loadCore(CodexEngine.java:179) ~[?:?]
        at studio.magemonkey.codex.CodexPlugin.onEnable(CodexPlugin.java:92) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:270) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.generator.WorldInfo
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:155) ~[patched_1.16.5.jar:git-Paper-794]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-794]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 12 more

**Comment by Travja** [comment]
Could you share your whole startup log?

**Comment by Ghost067** [comment]
[2024-04-13-4.log](https://github.com/promcteam/codex/files/14965569/2024-04-13-4.log)

This txt file is the boot log.

**Comment by Travja** [comment]
If you're on Discord, a new build should be coming shortly that should resolve this

**Comment by Ghost067** [comment]
I'm on Discord, but I'm in a bit of a hurry to use the plugin, I hope you can fix this soon, thank you very much!

**Comment by Travja** [comment]
Looks like it built properly, but didn't get posted... Sometimes it takes some time to show up

**Comment by Travja** [comment]
Nevermind, looks like it posted.

**Comment by Ghost067** [comment]
[latest.log](https://github.com/promcteam/codex/files/14965644/latest.log)

I'm sorry, it looks like there are still some problems with the plugin, here is the log file, please go and fix it again, thank you!

**Comment by Travja** [comment]
New build is up
